# Physical AI System 기본 설정 파일
# PHI-3.5 내장 Developmental Robotics & Embodied AI 시스템

system:
  name: "Physical AI System"
  version: "2.0.0-phi35"
  environment: "development"  # development, production, simulation
  debug_mode: true
  mock_hardware: true  # 하드웨어 없이 시뮬레이션 모드

foundation_model:
  model_type: "phi35"
  phi35:
    model_name: "microsoft/Phi-3.5-mini-instruct"
    device: "auto"  # auto, cpu, cuda, mps
    cache_dir: "models/cache"
    max_length: 2048
    temperature: 0.7
    top_p: 0.9
    learning_config:
      enabled: true
      learning_rate: 0.01
      memory_size: 1000
    training_output_dir: "models/slm_foundation"
    num_epochs: 3
    batch_size: 4
    learning_rate: 5e-5

developmental_learning:
  skill_acquisition:
    success_threshold: 0.8
    practice_iterations: 10
    learning_rate: 0.1
    exploration_rate: 0.3
  autonomous_learning:
    enabled: true
    exploration_interval: 900  # 15분
    max_exploration_time: 300  # 5분
  memory:
    max_episodic_memories: 5000
    max_semantic_patterns: 1000
    memory_decay_rate: 0.95
  curriculum:
    stages:
      - name: "basic_movement"
        difficulty: 1
        focus: "기본 이동 스킬"
      - name: "object_recognition"
        difficulty: 2
        focus: "객체 인식 및 분류"
      - name: "simple_grasp"
        difficulty: 3
        focus: "기본 잡기 동작"
      - name: "precise_manipulation"
        difficulty: 5
        focus: "정밀 조작"
      - name: "collaborative_task"
        difficulty: 7
        focus: "인간-로봇 협업"

agent_execution:
  motion_control:
    max_velocity: 2.0  # m/s
    max_acceleration: 5.0  # m/s²
    position_accuracy: 0.005  # m
    trajectory_smoothing: true
  safety:
    emergency_stop_distance: 0.02  # m
    monitoring_frequency: 20  # Hz
    collision_detection: true
    human_safety_zone: 0.5  # m
    force_limits:
      max_gripper_force: 50.0  # N
      max_joint_torque: 100.0  # Nm
  performance:
    execution_timeout: 300  # seconds
    retry_attempts: 3
    adaptive_speed: true

hardware_abstraction:
  sensors:
    vision:
      enabled: true
      resolution: [640, 480]
      fps: 30
      calibration_auto: true
    tactile:
      enabled: true
      sensitivity: 0.1
      calibration_auto: true
    imu:
      enabled: true
      update_rate: 100  # Hz
      calibration_auto: true
  actuators:
    joints:
      max_velocity: 2.0  # rad/s
      position_accuracy: 0.005  # rad
      torque_limits: [100.0, 100.0, 100.0, 50.0, 50.0, 25.0]  # Nm
    gripper:
      max_force: 50.0  # N
      position_accuracy: 0.001  # m
  communication:
    protocol: "ethernet"  # ethernet, can, serial
    timeout: 1.0  # seconds
    retry_attempts: 3

simulation:
  physics_engine: "pybullet"  # pybullet, mujoco
  gui_mode: true
  time_step: 0.01  # seconds
  gravity: [0, 0, -9.81]
  max_simulation_time: 3600  # seconds
  collision_detection: true
  visualization:
    enabled: true
    camera_position: [2, 2, 2]
    camera_target: [0, 0, 0]

monitoring:
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file_path: "logs/physical_ai.log"
    max_file_size: "10MB"
    backup_count: 5
  metrics:
    collection_interval: 1.0  # seconds
    storage_duration: 86400  # 24 hours
    export_format: "json"
  alerts:
    enabled: true
    email_notifications: false
    slack_webhook: ""
    critical_errors: true
    performance_warnings: true

web_interface:
  enabled: true
  host: "localhost"
  port: 5001
  debug: true
  cors_enabled: true
  session_timeout: 3600  # seconds
  max_connections: 100

distributed:
  enabled: false
  ray_cluster:
    head_node: "localhost:10001"
    worker_nodes: []
    resources:
      cpu: 4
      memory: "8GB"
      gpu: 0
  memory_sharing:
    redis_host: "localhost"
    redis_port: 6379
    redis_db: 0

security:
  authentication: false
  ssl_enabled: false
  api_rate_limit: 100  # requests per minute
  data_encryption: false
  access_control:
    allowed_ips: ["127.0.0.1", "localhost"]
    admin_users: []

backup:
  enabled: true
  schedule: "daily"  # daily, weekly, monthly
  retention_days: 30
  backup_path: "backups/"
  include_models: true
  include_logs: true
  compression: true
